version: '3'
services:
  drawer:
    build: .
    image: app
    environment:
      - DISPLAY=${HOSTNAME}${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - '8083:8083'
    depends_on:
      - influx

  influx:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=bz
